USE league_db;
CREATE TABLE Players (
    PlayerID CHAR(5) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Nationality VARCHAR(50) NOT NULL,
    DoB DATE NOT NULL,
    Role VARCHAR(50),
    BowlingStyle VARCHAR(50),
    BattingStyle VARCHAR(50),
    team_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (team_id) REFERENCES Teams(team_id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

INSERT INTO Players (PlayerID, Name, Nationality, DoB, Role, BowlingStyle, BattingStyle, team_id, created_at)
VALUES 
('CSK1', 'Ruturaj Gaikwad', 'India', '1997-01-31', 'Batsman', NULL, 'Right-hand bat', 1, NOW()),
('CSK2', 'Shivam Dube', 'India', '1993-06-26', 'All-rounder', 'Right-arm medium', 'Left-hand bat', 1, NOW()),
('CSK3', 'Daryl Mitchell', 'New Zealand', '1991-05-20', 'All-rounder', 'Right-arm fast', 'Right-hand bat', 1, NOW()),
('CSK4', 'Ravindra Jadeja', 'India', '1988-12-06', 'All-rounder', 'Left-arm orthodox', 'Left-hand bat', 1, NOW()),
('CSK5', 'Ajinkya Rahane', 'India', '1988-06-06', 'Batsman', NULL, 'Right-hand bat', 1, NOW()),
('CSK6', 'Rachin Ravindra', 'New Zealand', '1999-11-18', 'All-rounder', 'Left-arm orthodox', 'Left-hand bat', 1, NOW()),
('CSK7', 'MS Dhoni', 'India', '1981-07-07', 'Wicketkeeper-batsman', NULL, 'Right-hand bat', 1, NOW()),
('CSK8', 'Moeen Ali', 'England', '1987-06-18', 'All-rounder', 'Right-arm offbreak', 'Left-hand bat', 1, NOW()),
('CSK9', 'Sameer Rizwi', 'India', '1994-10-15', 'Batsman', NULL, 'Right-hand bat', 1, NOW()),
('CSK10', 'Shardul Thakur', 'India', '1991-10-16', 'Bowler', 'Right-arm medium', 'Right-hand bat', 1, NOW()),
('CSK11', 'Mitchell Santner', 'New Zealand', '1992-02-05', 'Bowler', 'Left-arm orthodox', 'Left-hand bat', 1, NOW()),
('DC001', 'Rishabh Pant', 'Indian', '1997-10-04', 'Batsman/Wicketkeeper', NULL, 'Left-hand bat', 2, NOW()),
('DC002', 'Tristan Stubbs', 'South African', '2000-08-14', 'Batsman', NULL, 'Right-hand bat', 2, NOW()),
('DC003', 'Jake Fraser-McGurk', 'Australian', '2002-04-28', 'Batsman', NULL, 'Right-hand bat', 2, NOW()),
('DC004', 'Abishek Porel', 'Indian', '2002-10-04', 'Batsman', NULL, 'Left-hand bat', 2, NOW()),
('DC005', 'Axar Patel', 'Indian', '1994-01-20', 'All-rounder', 'Left-arm orthodox', 'Left-hand bat', 2, NOW()),
('DC006', 'Prithvi Shaw', 'Indian', '1999-11-09', 'Batsman', NULL, 'Right-hand bat', 2, NOW()),
('DC007', 'Shai Hope', 'West Indian', '1993-11-10', 'Batsman', NULL, 'Right-hand bat', 2, NOW()),
('DC008', 'David Warner', 'Australian', '1986-10-27', 'Batsman', NULL, 'Left-hand bat', 2, NOW()),
('DC009', 'Mitchell Marsh', 'Australian', '1991-10-20', 'All-rounder', 'Right-arm fast-medium', 'Right-hand bat', 2, NOW()),
('DC010', 'Kuldeep Yadav', 'Indian', '1994-12-14', 'Bowler', 'Left-arm chinaman', 'Left-hand bat', 2, NOW()),
('DC011', 'Mukesh Kumar', 'Indian', '1993-02-12', 'Bowler', 'Right-arm medium', 'Right-hand bat', 2, NOW()),
('KKR1', 'Sunil Narine', 'West Indies', '1988-05-26', 'All-rounder', 'Right-arm offbreak', 'Right-hand bat', 3, NOW()),
('KKR2', 'Phil Salt', 'England', '1996-06-28', 'Batsman', NULL, 'Right-hand bat', 3, NOW()),
('KKR3', 'Venkatesh Iyer', 'India', '1996-12-25', 'All-rounder', 'Right-arm medium', 'Right-hand bat', 3, NOW()),
('KKR4', 'Shreyas Iyer', 'India', '1994-12-06', 'Batsman', 'Right-arm offbreak', 'Right-hand bat', 3, NOW()),
('KKR5', 'Andre Russell', 'West Indies', '1988-04-29', 'All-rounder', 'Right-arm fast', 'Right-hand bat', 3, NOW()),
('KKR6', 'Varun Chakaravarthy', 'India', '1991-08-29', 'Bowler', 'Right-arm offbreak', 'Right-hand bat', 3, NOW()),
('KKR7', 'Harshit Rana', 'India', '1998-05-12', 'Bowler', 'Right-arm medium', 'Right-hand bat', 3, NOW()),
('KKR8', 'Mitchell Starc', 'Australia', '1990-01-30', 'Bowler', 'Left-arm fast', 'Left-hand bat', 3, NOW()),
('KKR9', 'Vaibhav Arora', 'India', '1994-06-19', 'Bowler', 'Right-arm medium', 'Right-hand bat', 3, NOW()),
('KKR10', 'Anukul Roy', 'India', '1998-11-30', 'Bowler', 'Slow left-arm orthodox', 'Left-hand bat', 3, NOW()),
('KKR11', 'Rahmanullah Gurbaz', 'Afghanistan', '2002-06-22', 'Wicketkeeper', NULL, 'Right-hand bat', 3, NOW()),
('LSG1', 'K L Rahul', 'India', '1992-04-18', 'Batsman', NULL, 'Right-hand bat', 4, NOW()),
('LSG2', 'Nicholas Pooran', 'West Indies', '1995-10-02', 'Batsman', NULL, 'Left-hand bat', 4, NOW()),
('LSG3', 'Marcus Stoinis', 'Australia', '1989-08-16', 'All-rounder', 'Right-arm medium-fast', 'Right-hand bat', 4, NOW()),
('LSG4', 'Quinton De Kock', 'South Africa', '1992-12-17', 'Wicketkeeper', NULL, 'Left-hand bat', 4, NOW()),
('LSG5', 'Ayush Badoni', 'India', '1999-09-28', 'Batsman', NULL, 'Right-hand bat', 4, NOW()),
('LSG6', 'Deepak Hooda', 'India', '1995-04-19', 'Batsman', 'Right-arm offbreak', 'Right-hand bat', 4, NOW()),
('LSG7', 'Krunal Pandya', 'India', '1991-03-24', 'All-rounder', 'Left-arm orthodox', 'Left-hand bat', 4, NOW()),
('LSG8', 'Ravi Bishnoi', 'India', '2000-09-05', 'Bowler', 'Legbreak googly', 'Right-hand bat', 4, NOW()),
('LSG9', 'Mohsin Khan', 'India', '1998-11-15', 'Bowler', 'Right-arm fast-medium', 'Right-hand bat', 4, NOW()),
('LSG10', 'Mayank Yadav', 'India', '2001-06-10', 'Bowler', 'Right-arm fast-medium', 'Right-hand bat', 4, NOW()),
('LSG11', 'Naveen-Ul-Haq', 'Afghanistan', '1999-09-20', 'Bowler', 'Right-arm fast', 'Right-hand bat', 4, NOW()),
('RR1', 'Riyan Parag', 'India', '2001-11-10', 'Batsman', NULL, 'Right-hand bat', 5, NOW()),
('RR2', 'Sanju Samson', 'India', '1994-11-11', 'Wicketkeeper-batsman', NULL, 'Right-hand bat', 5, NOW()),
('RR3', 'Yashasvi Jaiswal', 'India', '2001-12-28', 'Batsman', NULL, 'Left-hand bat', 5, NOW()),
('RR4', 'Jos Buttler', 'England', '1990-09-08', 'Wicketkeeper-batsman', NULL, 'Right-hand bat', 5, NOW()),
('RR5', 'Dhruv Jurel', 'India', '2001-12-07', 'Wicketkeeper-batsman', NULL, 'Right-hand bat', 5, NOW()),
('RR6', 'Shimron Hetmyer', 'West Indies', '1996-12-26', 'Batsman', NULL, 'Left-hand bat', 5, NOW()),
('RR7', 'Rovman Powell', 'West Indies', '1993-07-23', 'All-rounder', 'Right-arm medium', 'Right-hand bat', 5, NOW()),
('RR8', 'Ravichandran Ashwin', 'India', '1986-09-17', 'All-rounder', 'Right-arm offbreak', 'Right-hand bat', 5, NOW()),
('RR9', 'Yuzvendra Chahal', 'India', '1990-07-23', 'Bowler', 'Legbreak googly', 'Right-hand bat', 5, NOW()),
('RR10', 'Trent Boult', 'New Zealand', '1989-07-22', 'Bowler', 'Left-arm fast-medium', 'Right-hand bat', 5, NOW()),
('RR11', 'Jason Holder', 'West Indies', '1991-11-05', 'All-rounder', 'Right-arm fast-medium', 'Right-hand bat', 5, NOW()),
('MI1', 'Rohit Sharma', 'India', '1987-04-30', 'Batsman', NULL, 'Right-hand bat', 6, NOW()),
('MI2', 'Tilak Varma', 'India', '2001-08-20', 'Batsman', NULL, 'Left-hand bat', 6, NOW()),
('MI3', 'Suryakumar Yadav', 'India', '1990-09-14', 'Batsman', NULL, 'Right-hand bat', 6, NOW()),
('MI4', 'Ishan Kishan', 'India', '1998-07-18', 'Batsman', NULL, 'Left-hand bat', 6, NOW()),
('MI5', 'Tim David', 'Singapore', '1996-11-14', 'Batsman', NULL, 'Right-hand bat', 6, NOW()),
('MI6', 'Hardik Pandya', 'India', '1993-10-11', 'All-rounder', 'Right-arm medium', 'Right-hand bat', 6, NOW()),
('MI7', 'Mohammad Nabi', 'Afghanistan', '1985-01-01', 'All-rounder', 'Right-arm offbreak', 'Right-hand bat', 6, NOW()),
('MI8', 'Piyush Chawla', 'India', '1989-12-24', 'Bowler', 'Legbreak', 'Left-hand bat', 6, NOW()),
('MI9', 'Gerald Coetzee', 'South Africa', '1996-08-25', 'Bowler', 'Right-arm fast', 'Right-hand bat', 6, NOW()),
('MI10', 'Jasprit Bumrah', 'India', '1993-12-06', 'Bowler', 'Right-arm fast', 'Right-hand bat', 6, NOW()),
('MI11', 'Shams Mulani', 'India', '1996-12-14', 'All-rounder', 'Slow left-arm orthodox', 'Left-hand bat', 6, NOW()),
('PBK1', 'Shashank Singh', 'India', '1995-03-17', 'Batsman', NULL, 'Right-hand bat', 7, NOW()),
('PBK2', 'Prabhsimran Singh', 'India', '2000-11-11', 'Batsman', NULL, 'Right-hand bat', 7, NOW()),
('PBK3', 'Jonny Bairstow', 'England', '1989-09-26', 'Batsman', NULL, 'Right-hand bat', 7, NOW()),
('PBK4', 'Sam Curran', 'England', '1998-06-03', 'All-rounder', 'Left-arm medium-fast', 'Left-hand bat', 7, NOW()),
('PBK6', 'Jitesh Sharma', 'India', '1993-11-03', 'Wicketkeeper-batsman', NULL, 'Right-hand bat', 7, NOW()),
('PBK7', 'Shikhar Dhawan', 'India', '1985-12-05', 'Batsman', NULL, 'Left-hand bat', 7, NOW()),
('PBK8', 'Liam Livingstone', 'England', '1993-08-04', 'All-rounder', 'Right-arm offbreak', 'Right-hand bat', 7, NOW()),
('PBK9', 'Harpreet Brar', 'India', '1995-09-16', 'All-rounder', 'Slow left-arm orthodox', 'Left-hand bat', 7, NOW()),
('PBK10', 'Harshal Patel', 'India', '1990-11-23', 'Bowler', 'Right-arm medium', 'Right-hand bat', 7, NOW()),
('PBK11', 'Arshdeep Singh', 'India', '1999-02-05', 'Bowler', 'Left-arm fast-medium', 'Left-hand bat', 7, NOW()),
('PBK5', 'Kagiso Rabada', 'South Africa', '1995-05-25', 'Bowler', 'Right-arm fast', 'Right-hand bat', 7, NOW()),
('RCB01', 'Virat Kohli', 'Indian', '1988-11-05', 'Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB02', 'Faf du Plessis', 'South African', '1984-07-13', 'Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB03', 'Glenn Maxwell', 'Australian', '1988-10-14', 'All-rounder', 'Right-arm offbreak', 'Right-hand bat', 8,NOW()),
('RCB04', 'Rajat Patidar', 'Indian', '1993-06-01', 'Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB05', 'Yash Dayal', 'Indian', '1990-11-23', 'Bowler', 'Right-arm medium-fast', 'Right-hand bat', 8,NOW()),
('RCB06', 'Wanindu Hasaranga', 'Sri Lankan', '1997-07-29', 'All-rounder', 'Right-arm legbreak', 'Right-hand bat', 8,NOW()),
('RCB07', 'Mohammed Siraj', 'Indian', '1994-03-13', 'Bowler', 'Right-arm fast', 'Right-hand bat', 8,NOW()),
('RCB08', 'Josh Hazlewood', 'Australian', '1991-01-08', 'Bowler', 'Right-arm fast', 'Left-hand bat', 8,NOW()),
('RCB09', 'Dinesh Karthik', 'Indian', '1985-06-01', 'Wicketkeeper/Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB10', 'Shahbaz Ahmed', 'Indian', '1994-12-12', 'All-rounder', 'Left-arm orthodox', 'Left-hand bat', 8,NOW()),
('RCB11', 'Suyash Prabhudessai', 'Indian', '1997-12-06', 'Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB01', 'Virat Kohli', 'Indian', '1988-11-05', 'Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB02', 'Faf du Plessis', 'South African', '1984-07-13', 'Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB03', 'Glenn Maxwell', 'Australian', '1988-10-14', 'All-rounder', 'Right-arm offbreak', 'Right-hand bat', 8,NOW()),
('RCB04', 'Rajat Patidar', 'Indian', '1993-06-01', 'Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB05', 'Yash Dayal', 'Indian', '1990-11-23', 'Bowler', 'Right-arm medium-fast', 'Right-hand bat', 8,NOW()),
('RCB06', 'Wanindu Hasaranga', 'Sri Lankan', '1997-07-29', 'All-rounder', 'Right-arm legbreak', 'Right-hand bat', 8,NOW()),
('RCB07', 'Mohammed Siraj', 'Indian', '1994-03-13', 'Bowler', 'Right-arm fast', 'Right-hand bat', 8,NOW()),
('RCB08', 'Josh Hazlewood', 'Australian', '1991-01-08', 'Bowler', 'Right-arm fast', 'Left-hand bat', 8,NOW()),
('RCB09', 'Dinesh Karthik', 'Indian', '1985-06-01', 'Wicketkeeper/Batsman', NULL, 'Right-hand bat', 8,NOW()),
('RCB10', 'Shahbaz Ahmed', 'Indian', '1994-12-12', 'All-rounder', 'Left-arm orthodox', 'Left-hand bat', 8,NOW()),
('RCB11', 'Suyash Prabhudessai', 'Indian', '1997-12-06', 'Batsman', NULL, 'Right-hand bat', 8,NOW()),
('SRH01', 'Abhishek Sharma', 'Indian', '2000-09-04', 'Batsman', NULL, 'Left-hand bat', 9, CURRENT_TIMESTAMP),
('SRH02', 'Travis Head', 'Australian', '1993-12-29', 'Batsman', NULL, 'Left-hand bat', 9, CURRENT_TIMESTAMP),
('SRH03', 'Rahul Tripathi', 'Indian', '1991-03-02', 'Batsman', NULL, 'Right-hand bat', 9, CURRENT_TIMESTAMP),
('SRH04', 'Nitish Kumar Reddy', 'Indian', '2002-05-01', 'All-rounder', 'Right-arm medium', 'Right-hand bat', 9, CURRENT_TIMESTAMP),
('SRH05', 'Heinrich Klaasen', 'South African', '1991-07-30', 'Wicketkeeper', NULL, 'Right-hand bat', 9, CURRENT_TIMESTAMP),
('SRH06', 'Shahbaz Ahmed', 'Indian', '1994-12-11', 'All-rounder', 'Left-arm orthodox', 'Left-hand bat', 9, CURRENT_TIMESTAMP),
('SRH07', 'Abdul Samad', 'Indian', '2001-10-28', 'Batsman', NULL, 'Right-hand bat', 9, CURRENT_TIMESTAMP),
('SRH08', 'Sanvir Singh', 'Indian', '1999-01-08', 'Batsman', NULL, 'Right-hand bat', 9, CURRENT_TIMESTAMP),
('SRH09', 'Pat Cummins', 'Australian', '1993-05-08', 'Bowler', 'Right-arm fast', 'Right-hand bat', 9, CURRENT_TIMESTAMP),
('SRH10', 'Bhuvneshwar Kumar', 'Indian', '1990-02-05', 'Bowler', 'Right-arm medium', 'Right-hand bat', 9, CURRENT_TIMESTAMP),
('SRH11', 'Vijayakanth Viyaskanth', 'Sri Lankan', '2001-05-12', 'Bowler', 'Right-arm leg-spin', 'Right-hand bat', 9, CURRENT_TIMESTAMP),
('GT01', 'Shubman Gill', 'Indian', '1999-09-08', 'Batsman', NULL, 'Right-hand bat', 10, CURRENT_TIMESTAMP),
('GT02', 'Wriddhiman Saha', 'Indian', '1984-10-24', 'Wicketkeeper', NULL, 'Right-hand bat', 10, CURRENT_TIMESTAMP),
('GT03', 'Shahrukh Khan', 'Indian', '1995-05-27', 'All-rounder', 'Right-arm medium', 'Right-hand bat', 10, CURRENT_TIMESTAMP),
('GT04', 'David Miller', 'South African', '1989-06-10', 'Batsman', NULL, 'Left-hand bat', 10, CURRENT_TIMESTAMP),
('GT05', 'Rahul Tewatia', 'Indian', '1993-05-20', 'All-rounder', 'Left-arm leg-spin', 'Left-hand bat', 10, CURRENT_TIMESTAMP),
('GT06', 'Rashid Khan', 'Afghan', '1998-09-20', 'Bowler', 'Right-arm leg-spin', 'Right-hand bat', 10, CURRENT_TIMESTAMP),
('GT07', 'Mohammed Shami', 'Indian', '1990-09-03', 'Bowler', 'Right-arm fast', 'Right-hand bat', 10, CURRENT_TIMESTAMP),
('GT08', 'Alzarri Joseph', 'West Indian', '1996-11-20', 'Bowler', 'Right-arm fast', 'Right-hand bat', 10, CURRENT_TIMESTAMP),
('GT09', 'Sai Sudharsan', 'Indian', '2001-10-15', 'Batsman', NULL, 'Left-hand bat', 10, CURRENT_TIMESTAMP),
('GT10', 'Vijay Shankar', 'Indian', '1991-01-26', 'All-rounder', 'Right-arm medium', 'Right-hand bat', 10, CURRENT_TIMESTAMP),
('GT11', 'Joshua Little', 'Irish', '1999-11-01', 'Bowler', 'Left-arm fast', 'Right-hand bat', 10, CURRENT_TIMESTAMP);


